// <auto-generated />
namespace CosStay.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddResidents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResidents));
        
        string IMigrationMetadata.Id
        {
            get { return "201405130943311_AddResidents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
