// <auto-generated />
namespace CosStay.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PhotoReferencesWtf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhotoReferencesWtf));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241230277_PhotoReferencesWtf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
