// <auto-generated />
namespace CosStay.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NamedRooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NamedRooms));
        
        string IMigrationMetadata.Id
        {
            get { return "201404131132523_NamedRooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
